name: viviendaSocial
services:
  db:
    image: mariadb:11.3.2
    container_name: viviendaSocial-db
    environment:
      MARIADB_DATABASE: viviendaSocial_database
      MARIADB_USER: viviendaSocial_user
      MARIADB_PASSWORD: viviendaSocial_password
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - C:\Users\Hermes\Desktop\DAM\2ยบ\Acceso a Datos\mariadb_viviendaSocial:/var/lib/mysql
